// Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: 0BSD

/*
 * This source file was generated by the Gradle 'init' task
 */
package com.digitalasset.quickstart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;

/**
 * CantonVault backend application.
 *
 * Security is configured per-profile:
 * <ul>
 *   <li>{@code shared-secret} — demo/hackathon only (SharedSecretConfig)</li>
 *   <li>{@code oauth2} — production (OAuth2Config)</li>
 * </ul>
 *
 * If no security profile is active, Spring Boot's default auto-configuration
 * applies (form login with generated password), which is safe by default
 * but must be overridden in any deployed environment.
 */
@SpringBootApplication
@ConfigurationPropertiesScan("com.digitalasset.quickstart")
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("Starting CantonVault backend");
        try {
            SpringApplication.run(App.class, args);
        } catch (Exception e) {
            logger.error("Failed to start application", e);
            System.exit(2);
        }
    }
}
